name: Deploy to Easypanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://147.93.113.16:3000/api/deploy/d7f63ad281ca21ee489eb6dcd8244cbc679e33fd6f11e296'
          method: 'POST'
          timeout: 10000
